[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "v0.11.8"

[[constraint]]
  branch = "cm-update-confluent"
  name = "github.com/Mongey/ksql"

[[constraint]]
  name = "github.com/Mongey/terraform-provider-kafka"
  version = "0.1.3"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
